if Rails.env == 'development' || Rails.env == 'test'
  FACEBOOK_LOOPED_OAUTH_ID = ENV["FACEBOOK_LOOPED_OAUTH_ID_DEV"]
  FACEBOOK_LOOPED_OAUTH_SECRET = ENV["FACEBOOK_LOOPED_OAUTH_SECRET_DEV"]
else
  # Production
  FACEBOOK_LOOPED_OAUTH_ID = ENV["FACEBOOK_LOOPED_OAUTH_ID"]
  FACEBOOK_LOOPED_OAUTH_SECRET = ENV["FACEBOOK_LOOPED_OAUTH_SECRET"]
end